using Xunit;
using SliderSorter.Core;

namespace SliderSorter.Tests;

public class ModListParserTests
{
    [Fact]
    public void ParsesPrefixesCommentsAndSpecials()
    {
        const string content = """
            # This file was automatically generated by Mod Organizer.

            +CBBE
            -Disabled Mod
            *Unmanaged DLC
            +== Section ==_separator
            +SomeMod backup0
            +Overwrite
            +SkyUI SE
            NoPrefixMod

            """;

        var entries = ModListParser.ParseContent(content);

        // 分隔符保留（用于重建 MO2 视图）；备份 / Overwrite / 注释 / 空行跳过
        var names = entries.Select(e => e.Name).ToArray();
        Assert.Equal(new[] { "CBBE", "Disabled Mod", "Unmanaged DLC", "== Section ==_separator", "SkyUI SE", "NoPrefixMod" }, names);

        Assert.True(entries[0].Enabled);
        Assert.False(entries[1].Enabled);
        Assert.True(entries[2].IsForeign);
        Assert.True(entries[3].IsSeparator);
        Assert.True(entries[4].Enabled);
        Assert.True(entries[5].Enabled);
    }

    [Fact]
    public void GetEnabledModDirectories_ExcludesSeparators()
    {
        using var temp = new TempDir();
        var mods = temp.Sub("mods");
        Directory.CreateDirectory(System.IO.Path.Combine(mods, "Real Mod"));
        Directory.CreateDirectory(System.IO.Path.Combine(mods, "Section_separator"));

        var entries = ModListParser.ParseContent("+Real Mod\n+Section_separator\n");
        var enabled = ModListParser.GetEnabledModDirectories(entries, mods);

        Assert.Single(enabled);
        Assert.Equal("Real Mod", enabled[0].Entry.Name);
    }

    [Fact]
    public void PriorityFollowsLineOrder_FirstLineIsHighest()
    {
        const string content = "+BottomOfLeftPane\n+Middle\n+TopOfLeftPane\n";
        var entries = ModListParser.ParseContent(content);

        Assert.True(entries[0].Priority < entries[1].Priority);
        Assert.True(entries[1].Priority < entries[2].Priority);
    }

    [Fact]
    public void GetEnabledModDirectories_SkipsMissingFoldersAndForeign()
    {
        using var temp = new TempDir();
        var mods = temp.Sub("mods");
        Directory.CreateDirectory(System.IO.Path.Combine(mods, "Real Mod"));
        Directory.CreateDirectory(System.IO.Path.Combine(mods, "Second Mod"));

        var entries = ModListParser.ParseContent("+Real Mod\n-Ghost Mod\n*Foreign\n+Second Mod\n");
        var enabled = ModListParser.GetEnabledModDirectories(entries, mods);

        Assert.Equal(2, enabled.Count);
        Assert.Equal("Real Mod", enabled[0].Entry.Name);
        Assert.Equal("Second Mod", enabled[1].Entry.Name);
    }
}
