using Xunit;
using SliderSorter.Core;

namespace SliderSorter.Tests;

public class ModListParserTests
{
    [Fact]
    public void ParsesPrefixesCommentsAndSpecials()
    {
        const string content = """
            # This file was automatically generated by Mod Organizer.

            +CBBE
            -Disabled Mod
            *Unmanaged DLC
            +== Section ==_separator
            +SomeMod backup0
            +Overwrite
            +SkyUI SE
            NoPrefixMod

            """;

        var entries = ModListParser.ParseContent(content);

        // 分隔符保留（用于重建 MO2 视图）；备份 / Overwrite / 注释 / 空行跳过
        var names = entries.Select(e => e.Name).ToArray();
        Assert.Equal(new[] { "CBBE", "Disabled Mod", "Unmanaged DLC", "== Section ==_separator", "SkyUI SE", "NoPrefixMod" }, names);

        Assert.True(entries[0].Enabled);
        Assert.False(entries[1].Enabled);
        Assert.True(entries[2].IsForeign);
        Assert.True(entries[3].IsSeparator);
        Assert.True(entries[4].Enabled);
        Assert.True(entries[5].Enabled);
    }

    [Fact]
    public void GetEnabledModDirectories_ExcludesSeparators()
    {
        using var temp = new TempDir();
        var mods = temp.Sub("mods");
        Directory.CreateDirectory(System.IO.Path.Combine(mods, "Real Mod"));
        Directory.CreateDirectory(System.IO.Path.Combine(mods, "Section_separator"));

        var entries = ModListParser.ParseContent("+Real Mod\n+Section_separator\n");
        var enabled = ModListParser.GetEnabledModDirectories(entries, mods);

        Assert.Single(enabled);
        Assert.Equal("Real Mod", enabled[0].Entry.Name);
    }

    [Fact]
    public void PriorityFollowsLineOrder_FirstLineIsHighest()
    {
        const string content = "+BottomOfLeftPane\n+Middle\n+TopOfLeftPane\n";
        var entries = ModListParser.ParseContent(content);

        Assert.True(entries[0].Priority < entries[1].Priority);
        Assert.True(entries[1].Priority < entries[2].Priority);
    }

    [Fact]
    public void GetEnabledModDirectories_SkipsMissingFoldersAndForeign()
    {
        using var temp = new TempDir();
        var mods = temp.Sub("mods");
        Directory.CreateDirectory(System.IO.Path.Combine(mods, "Real Mod"));
        Directory.CreateDirectory(System.IO.Path.Combine(mods, "Second Mod"));

        var entries = ModListParser.ParseContent("+Real Mod\n-Ghost Mod\n*Foreign\n+Second Mod\n");
        var enabled = ModListParser.GetEnabledModDirectories(entries, mods);

        Assert.Equal(2, enabled.Count);
        Assert.Equal("Real Mod", enabled[0].Entry.Name);
        Assert.Equal("Second Mod", enabled[1].Entry.Name);
    }


    /// <summary>「跳过备份模组」只该跳过名字**结尾**就是 backup（可带序号/括号）的那些。
    /// 早先的表达式 <c>^.*backup[0-9]*$</c> 允许任意前缀且数字可为零位，于是任何以 backup
    /// 结尾的模组名都被无声丢掉（用户只会觉得整合包坏了），而 MO2 常见的
    /// <c>X (Backup 1)</c> 反而匹配不上——两头都不讨好。</summary>
    [Theory]
    [InlineData("SomeMod backup0", true)]              // 真备份：丢
    [InlineData("SomeMod (Backup 1)", true)]           // MO2 里的括号写法：丢
    [InlineData("SomeMod - backup", true)]             // 结尾整段就是 backup：丢
    [InlineData("Backup", true)]                       // 名字就叫 Backup：丢
    [InlineData("MCM Memory - Settings Backup and Restore", false)] // backup 只是名字中间一个词：留
    [InlineData("MyBackup", false)]                    // 连词都不是：留
    [InlineData("Kalilies Brows backup fix", false)]   // 结尾不是 backup：留
    public void OnlyTrailingBackupNamesAreSkipped(string name, bool dropped)
    {
        var entries = ModListParser.ParseContent($"+{name}\n");
        Assert.Equal(!dropped, entries.Count == 1);
        if (!dropped)
            Assert.Equal(name, entries[0].Name);
    }
}
